<?php

namespace Modules\Core\Models;

/**
 * Static-analysis mixin for tenant domain relations delegated at runtime.
 *
 * @see TenantDomainAggregateService
 * @see TenancyServiceProvider
 *
 * @method \Illuminate\Database\Eloquent\Relations\HasMany academicYears()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany departments()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany academicPeriods()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany curricula()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany subjects()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany students()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany teachers()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany schoolClasses()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany classStudents()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany schedules()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany attendances()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany assessments()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany assessmentItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studentAssessmentAnswers()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studentGrades()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany violationTypes()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany violations()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany achievementTypes()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studentAchievements()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany faculties()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studyPrograms()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany courses()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany lecturers()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany collageStudents()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany courseOfferings()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studyPlans()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studyPlanItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studyResults()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany feederLogs()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany theses()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany admissionPeriods()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany applicants()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany examSchedules()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany examResults()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany registrations()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany chartOfAccounts()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany tuitionTypes()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studentInvoices()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany studentInvoiceItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany payments()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany journalEntries()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany journalEntryLines()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany budgets()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany bookCategories()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany books()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany bookCopies()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany members()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany bookReservations()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany libraryPolicies()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany loans()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany fines()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany positions()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany shifts()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany employees()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany employmentContracts()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany attendanceLogs()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany leaveRequests()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany payrollComponents()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany salarySlips()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany salarySlipComponents()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany kpiTemplates()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany kpiIndicators()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany kpiScores()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany vendors()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany procurementCategories()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany procurementItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany purchaseRequisitions()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany purchaseRequisitionItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany requestForQuotations()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany rfqItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany rfqVendors()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany purchaseOrders()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany purchaseOrderItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany goodsReceipts()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany goodsReceiptItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany vendorBills()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany vendorBillItems()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany auditLogs()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany fileUploads()
 * @method \Illuminate\Database\Eloquent\Relations\MorphMany auditableLogs()
 * @method \Illuminate\Database\Eloquent\Relations\MorphMany attachedFiles()
 */
abstract class TenantDelegatedRelations {}
