<?php

namespace Modules\Procurement\Filament\Resources\PurchaseRequisitions\RelationManagers;

use Modules\Workflow\Filament\RelationManagers\WorkflowInstancesRelationManager as BaseWorkflowInstancesRelationManager;

class WorkflowInstancesRelationManager extends BaseWorkflowInstancesRelationManager {}
