<?php

namespace Modules\Inventory\Filament\Resources\StockAdjustments\RelationManagers;

use Modules\Workflow\Filament\RelationManagers\WorkflowInstancesRelationManager as BaseWorkflowInstancesRelationManager;

class WorkflowInstancesRelationManager extends BaseWorkflowInstancesRelationManager {}
