<?php

namespace Modules\Core\Filament\Support\Navigation;

use BackedEnum;
use Filament\Support\Icons\Heroicon;

class NavigationIconResolver
{
    /**
     * @param  class-string  $resourceClass
     */
    public static function resolve(string $resourceClass): BackedEnum
    {
        $resourceName = str(class_basename($resourceClass))
            ->beforeLast('Resource')
            ->kebab()
            ->toString();

        return match (true) {
            str_contains($resourceName, 'academic-year'),
            str_contains($resourceName, 'academic-period'),
            str_contains($resourceName, 'admission-period') => Heroicon::CalendarDateRange,
            str_contains($resourceName, 'announcement'),
            str_contains($resourceName, 'broadcast') => Heroicon::Megaphone,
            str_contains($resourceName, 'assessment-answer'),
            str_contains($resourceName, 'assessment-item') => Heroicon::ClipboardDocumentCheck,
            str_contains($resourceName, 'assessment'),
            str_contains($resourceName, 'exam-result') => Heroicon::DocumentCheck,
            str_contains($resourceName, 'attendance') => Heroicon::CalendarDays,
            str_contains($resourceName, 'audit'),
            str_contains($resourceName, 'log') => Heroicon::DocumentMagnifyingGlass,
            str_contains($resourceName, 'author') => Heroicon::PencilSquare,
            str_contains($resourceName, 'book-copy'),
            str_contains($resourceName, 'stock-take-item') => Heroicon::Square2Stack,
            str_contains($resourceName, 'book-reservation') => Heroicon::BookmarkSquare,
            str_contains($resourceName, 'book'),
            str_contains($resourceName, 'course') => Heroicon::BookOpen,
            str_contains($resourceName, 'budget'),
            str_contains($resourceName, 'invoice'),
            str_contains($resourceName, 'tuition') => Heroicon::DocumentCurrencyDollar,
            str_contains($resourceName, 'campaign') => Heroicon::Gift,
            str_contains($resourceName, 'capacity') => Heroicon::ChartBarSquare,
            str_contains($resourceName, 'category'),
            str_contains($resourceName, 'collection-type'),
            str_contains($resourceName, 'subject'),
            str_contains($resourceName, 'type') => Heroicon::Tag,
            str_contains($resourceName, 'chart-of-account') => Heroicon::Calculator,
            str_contains($resourceName, 'city'),
            str_contains($resourceName, 'country'),
            str_contains($resourceName, 'district'),
            str_contains($resourceName, 'province'),
            str_contains($resourceName, 'village') => Heroicon::MapPin,
            str_contains($resourceName, 'clinic') => Heroicon::Heart,
            str_contains($resourceName, 'contract'),
            str_contains($resourceName, 'legal-document') => Heroicon::Scale,
            str_contains($resourceName, 'counseling') => Heroicon::ChatBubbleLeftRight,
            str_contains($resourceName, 'curriculum'),
            str_contains($resourceName, 'training') => Heroicon::AcademicCap,
            str_contains($resourceName, 'department'),
            str_contains($resourceName, 'faculty'),
            str_contains($resourceName, 'organization'),
            str_contains($resourceName, 'tenant') => Heroicon::BuildingOffice2,
            str_contains($resourceName, 'document'),
            str_contains($resourceName, 'letter') => Heroicon::DocumentText,
            str_contains($resourceName, 'dormitory'),
            str_contains($resourceName, 'room') => Heroicon::HomeModern,
            str_contains($resourceName, 'employee'),
            str_contains($resourceName, 'lecturer'),
            str_contains($resourceName, 'teacher') => Heroicon::Identification,
            str_contains($resourceName, 'event') => Heroicon::Calendar,
            str_contains($resourceName, 'extracurricular') => Heroicon::Sparkles,
            str_contains($resourceName, 'file-upload') => Heroicon::CloudArrowUp,
            str_contains($resourceName, 'fine'),
            str_contains($resourceName, 'payment') => Heroicon::CreditCard,
            str_contains($resourceName, 'goods-receipt') => Heroicon::InboxArrowDown,
            str_contains($resourceName, 'helpdesk'),
            str_contains($resourceName, 'ticket') => Heroicon::Lifebuoy,
            str_contains($resourceName, 'iso-control'),
            str_contains($resourceName, 'quality-standard') => Heroicon::ShieldCheck,
            str_contains($resourceName, 'journal-entry') => Heroicon::ClipboardDocumentList,
            str_contains($resourceName, 'kpi') => Heroicon::PresentationChartLine,
            str_contains($resourceName, 'lead'),
            str_contains($resourceName, 'applicant'),
            str_contains($resourceName, 'registration') => Heroicon::UserPlus,
            str_contains($resourceName, 'leave-request') => Heroicon::PaperAirplane,
            str_contains($resourceName, 'loan') => Heroicon::ArrowRightCircle,
            str_contains($resourceName, 'member') => Heroicon::UserCircle,
            str_contains($resourceName, 'menu') => Heroicon::QueueList,
            str_contains($resourceName, 'merch-order') => Heroicon::ShoppingBag,
            str_contains($resourceName, 'module') => Heroicon::PuzzlePiece,
            str_contains($resourceName, 'notification-template') => Heroicon::BellAlert,
            str_contains($resourceName, 'payroll'),
            str_contains($resourceName, 'salary') => Heroicon::Banknotes,
            str_contains($resourceName, 'policy') => Heroicon::ClipboardDocument,
            str_contains($resourceName, 'position') => Heroicon::Briefcase,
            str_contains($resourceName, 'procurement-item'),
            str_contains($resourceName, 'stock-item') => Heroicon::ArchiveBox,
            str_contains($resourceName, 'purchase-order'),
            str_contains($resourceName, 'purchase-requisition'),
            str_contains($resourceName, 'quotation'),
            str_contains($resourceName, 'rfq') => Heroicon::ShoppingCart,
            str_contains($resourceName, 'publisher') => Heroicon::BuildingLibrary,
            str_contains($resourceName, 'risk'),
            str_contains($resourceName, 'violation') => Heroicon::ExclamationTriangle,
            str_contains($resourceName, 'schedule'),
            str_contains($resourceName, 'shift'),
            str_contains($resourceName, 'timezone') => Heroicon::Clock,
            str_contains($resourceName, 'serial') => Heroicon::Newspaper,
            str_contains($resourceName, 'site') => Heroicon::GlobeAlt,
            str_contains($resourceName, 'software-license') => Heroicon::Key,
            str_contains($resourceName, 'stock-adjustment') => Heroicon::AdjustmentsHorizontal,
            str_contains($resourceName, 'stock-move') => Heroicon::ArrowsRightLeft,
            str_contains($resourceName, 'student-achievement') => Heroicon::Trophy,
            str_contains($resourceName, 'student-grade'),
            str_contains($resourceName, 'study-result') => Heroicon::ChartBar,
            str_contains($resourceName, 'student'),
            str_contains($resourceName, 'alumnus') => Heroicon::UserGroup,
            str_contains($resourceName, 'study-plan') => Heroicon::Map,
            str_contains($resourceName, 'subscription') => Heroicon::ReceiptPercent,
            str_contains($resourceName, 'thesis') => Heroicon::DocumentDuplicate,
            str_contains($resourceName, 'user') => Heroicon::Users,
            str_contains($resourceName, 'vehicle') => Heroicon::Truck,
            str_contains($resourceName, 'vendor-bill') => Heroicon::ReceiptRefund,
            str_contains($resourceName, 'vendor') => Heroicon::BuildingStorefront,
            str_contains($resourceName, 'visitor') => Heroicon::QrCode,
            str_contains($resourceName, 'warehouse') => Heroicon::ServerStack,
            str_contains($resourceName, 'webhook') => Heroicon::Signal,
            str_contains($resourceName, 'workflow-instance') => Heroicon::PlayCircle,
            str_contains($resourceName, 'workflow-step') => Heroicon::QueueList,
            str_contains($resourceName, 'workflow-transition') => Heroicon::ArrowPathRoundedSquare,
            str_contains($resourceName, 'workflow') => Heroicon::RectangleStack,
            default => Heroicon::Squares2x2,
        };
    }
}
