<?php

namespace Modules\Core\Support;

use Filament\Support\Icons\Heroicon;
use Illuminate\Support\Str;
use UnitEnum;

class FilamentUi
{
    /**
     * Exact phrases that need a natural Indonesian translation.
     *
     * @var array<string, string>
     */
    protected const PHRASES = [
        // ── Singular ────────────────────────────────────────────────────────────
        'Academic period' => 'Periode akademik',
        'Academic year' => 'Tahun akademik',
        'Achievement type' => 'Jenis prestasi',
        'Admission period' => 'Periode penerimaan',
        'Assessment item' => 'Item asesmen',
        'Attendance log' => 'Log kehadiran',
        'Attendance recap' => 'Rekapitulasi Absensi',
        'Audit log' => 'Log audit',
        'Navigation' => 'Navigasi',
        'Overview' => 'Ringkasan',
        'Favorites' => 'Favorit',
        'Add to favorites' => 'Tambah ke favorit',
        'Remove from favorites' => 'Hapus dari favorit',
        'Search menu' => 'Cari menu',
        'No menu found' => 'Menu tidak ditemukan',
        'All' => 'Semua',
        'Other' => 'Lainnya',
        'Book category' => 'Kategori buku',
        'Book copy' => 'Eksemplar buku',
        'Budget' => 'Anggaran',
        'Campus' => 'Kampus',
        'Chart of account' => 'Bagan akun',
        'Customer invoice' => 'Invoice pelanggan',
        'Customer invoice item' => 'Item invoice pelanggan',
        'City' => 'Kota',
        'Class student' => 'Siswa kelas',
        'Collage student' => 'Mahasiswa',
        'Core' => 'Inti',
        'Module Marketplace' => 'Marketplace Modul',
        'Module updated' => 'Modul diperbarui',
        'Branding Settings' => 'Pengaturan Branding',
        'Create Organization' => 'Buat Organisasi',
        'Branding updated' => 'Branding diperbarui',
        'Brand logo' => 'Logo merek',
        'Primary color' => 'Warna utama',
        'Currency' => 'Mata Uang',
        'Billing & Subscription' => 'Tagihan & Langganan',
        'Billing' => 'Tagihan',
        'Current Plan' => 'Paket Saat Ini',
        'Monthly Estimate' => 'Estimasi Bulanan',
        'Invoice History' => 'Riwayat Invoice',
        'Generate Invoice' => 'Buat Invoice',
        'Invoice generated' => 'Invoice berhasil dibuat',
        'Already billed' => 'Sudah ditagih bulan ini',
        'Payment error' => 'Terjadi kesalahan pembayaran',
        'Pay' => 'Bayar',
        'Subscription plan' => 'Paket langganan',
        'Price per seat' => 'Harga per pengguna',
        'Price per module' => 'Harga per modul',
        'Free seats' => 'Kursi gratis',
        'Free modules' => 'Modul gratis',
        'Grace period days' => 'Masa tenggang (hari)',
        'Country' => 'Negara',
        'Course offering' => 'Penawaran mata kuliah',
        'Course' => 'Mata kuliah',
        'Curriculum' => 'Kurikulum',
        'Department' => 'Departemen',
        'District' => 'Kecamatan',
        'Employee' => 'Karyawan',
        'Employment contract' => 'Kontrak kerja',
        'Enrollment' => 'Penerimaan',
        'Exam' => 'Ujian',
        'Exam definition' => 'Definisi ujian',
        'Title' => 'Judul',
        'Exam question builder' => 'Penyusun soal ujian',
        'Add question' => 'Tambah soal',
        'Total questions' => 'Total soal',
        'Total score' => 'Total skor',
        'Mark as ready' => 'Tandai siap',
        'Publish to runtime' => 'Publikasikan ke runtime',
        'Duplicate exam' => 'Duplikasi ujian',
        'Close exam' => 'Tutup ujian',
        'Sync participants' => 'Sinkronkan peserta',
        'Sync results' => 'Sinkronkan hasil',
        'Push to School Gradebook' => 'Kirim ke rapor School',
        'Push to Campus Gradebook' => 'Kirim ke rapor Campus',
        'School gradebook export finished.' => 'Ekspor rapor School selesai.',
        'Campus gradebook export finished.' => 'Ekspor rapor Campus selesai.',
        'Gradebook integration deferred; events dispatched.' => 'Integrasi rapor ditunda; event telah dikirim.',
        'Gradebook export logs' => 'Log ekspor rapor',
        'History of pushes to School or Campus gradebooks.' => 'Riwayat pengiriman ke rapor School atau Campus.',
        'Include cross-context questions' => 'Sertakan soal lintas konteks',
        'Exam marked as ready.' => 'Ujian ditandai siap.',
        'Exam published to runtime (stub).' => 'Ujian dipublikasikan ke runtime (stub).',
        'Exam published to runtime.' => 'Ujian dipublikasikan ke runtime.',
        'Exam republished to runtime.' => 'Ujian dipublikasikan ulang ke runtime.',
        'Republish to runtime' => 'Publikasikan ulang ke runtime',
        'Sync participants only' => 'Sinkronkan peserta saja',
        'Sync admin access' => 'Sinkronkan akses admin',
        'Participants synced to runtime.' => 'Peserta disinkronkan ke runtime.',
        'Admin access synced to runtime.' => 'Akses admin disinkronkan ke runtime.',
        'Runtime sync failed.' => 'Sinkronisasi runtime gagal.',
        'Runtime ID' => 'ID runtime',
        'Participant count' => 'Jumlah peserta',
        'Admin access count' => 'Jumlah akses admin',
        'Generate participants' => 'Generate peserta',
        'Results synced from runtime.' => 'Hasil disinkronkan dari runtime.',
        'Exam attempts' => 'Percobaan ujian',
        'Scores synced from Cloudflare runtime.' => 'Skor disinkronkan dari runtime Cloudflare.',
        'Exam results' => 'Hasil ujian',
        'Final scores synced from Cloudflare runtime.' => 'Skor akhir disinkronkan dari runtime Cloudflare.',
        'Exam answers' => 'Jawaban ujian',
        'Ai prompt template' => 'Template prompt AI',
        'Ai prompt templates' => 'Template prompt AI',
        'Workflow designer' => 'Perancang workflow',
        'New workflow' => 'Workflow baru',
        'Active' => 'Aktif',
        'Inactive' => 'Nonaktif',
        'Stored uppercase. Must be unique per tenant and organization.' => 'Disimpan huruf besar. Harus unik per tenant dan organisasi.',
        'Review synced answers and grade essay responses manually.' => 'Tinjau jawaban tersinkron dan nilai esai secara manual.',
        'Grade essay' => 'Nilai esai',
        'Essay graded successfully.' => 'Esai berhasil dinilai.',
        'Exam activity logs' => 'Log aktivitas ujian',
        'Proctoring and session events from the runtime.' => 'Acara proctoring dan sesi dari runtime.',
        'Activity Logs' => 'Log aktivitas',
        'Analytics' => 'Analitik',
        'Analytics overview' => 'Ringkasan analitik',
        'Insights based on synced results and answers.' => 'Wawasan berdasarkan hasil dan jawaban tersinkron.',
        'Export CSV' => 'Ekspor CSV',
        'Export Excel' => 'Ekspor Excel',
        'Open control room' => 'Buka control room',
        'Attempts' => 'Percobaan',
        'Answers' => 'Jawaban',
        'Results' => 'Hasil',
        'Participants' => 'Peserta',
        'Exam duplicated.' => 'Ujian diduplikasi.',
        'Exam closed.' => 'Ujian ditutup.',
        'Participant sync queued for runtime.' => 'Sinkronisasi peserta diantrekan ke runtime.',
        'Participants synced.' => 'Peserta disinkronkan.',
        'Current participants' => 'Peserta saat ini',
        'Exam participants' => 'Peserta ujian',
        'Generate from class' => 'Generate dari rombel',
        'Generate from course class' => 'Generate dari kelas kuliah',
        'Add participant' => 'Tambah peserta',
        'Import CSV' => 'Impor CSV',
        'Download import template' => 'Unduh template impor',
        'Export tokens CSV' => 'Ekspor CSV token',
        'Print token cards' => 'Cetak kartu token',
        'Regenerate token' => 'Regenerasi token',
        'Token regenerated.' => 'Token diregenerasi.',
        'Participants generated from class.' => 'Peserta digenerate dari rombel.',
        'Participants generated from course class.' => 'Peserta digenerate dari kelas kuliah.',
        'CSV import completed.' => 'Impor CSV selesai.',
        'Could not read CSV file.' => 'Tidak dapat membaca berkas CSV.',
        'Created' => 'Dibuat',
        'Skipped' => 'Dilewati',
        'School student' => 'Siswa sekolah',
        'Campus student' => 'Mahasiswa kampus',
        'Assigned' => 'Ditugaskan',
        'Started' => 'Dimulai',
        'Submitted' => 'Diserahkan',
        'Absent' => 'Tidak hadir',
        'Cancelled' => 'Dibatalkan',
        'Result sync queued for runtime.' => 'Sinkronisasi hasil diantrekan ke runtime.',
        'Stored attempt sync records' => 'Catatan sinkronisasi percobaan tersimpan',
        'Optional. Leave blank to use the question default score.' => 'Opsional. Kosongkan untuk memakai skor default soal.',
        'Practice' => 'Latihan',
        'Tryout' => 'Try out',
        'Placement' => 'Penempatan',
        'Ready' => 'Siap',
        'Exam question bank' => 'Bank soal ujian',
        'Download demo import CSV' => 'Unduh CSV impor demo',
        'Question import completed.' => 'Impor soal selesai.',
        'imported successfully.' => 'berhasil diimpor.',
        'failed to import. Open the import details for row-level errors.' => 'gagal diimpor. Buka detail impor untuk error per baris.',
        'Exam participant' => 'Peserta ujian',
        'Exam token' => 'Token ujian',
        'Exam question' => 'Soal ujian',
        'Academic context type' => 'Jenis konteks akademik',
        'School subject reference' => 'Referensi mata pelajaran',
        'School grade level reference' => 'Referensi tingkat kelas',
        'School curriculum reference' => 'Referensi kurikulum',
        'Campus course reference' => 'Referensi mata kuliah',
        'Campus study program reference' => 'Referensi program studi',
        'Standalone subject' => 'Mata pelajaran mandiri',
        'Standalone level' => 'Tingkat mandiri',
        'School references' => 'Referensi sekolah',
        'Campus references' => 'Referensi kampus',
        'Standalone references' => 'Referensi mandiri',
        'Question bank & classification' => 'Bank soal & klasifikasi',
        'Question body' => 'Isi soal',
        'Answer options' => 'Pilihan jawaban',
        'Option text' => 'Teks pilihan',
        'MI mapping' => 'Pemetaan MI',
        'OSN metadata' => 'Metadata OSN',
        'Olympiad subject' => 'Mata pelajaran olimpiade',
        'Olympiad level' => 'Tingkat olimpiade',
        'Skill codes' => 'Kode keterampilan',
        'Estimated time seconds' => 'Perkiraan waktu (detik)',
        'Logical intelligence' => 'Kecerdasan logis',
        'Linguistic intelligence' => 'Kecerdasan linguistik',
        'Visual intelligence' => 'Kecerdasan visual',
        'Kinesthetic intelligence' => 'Kecerdasan kinestetik',
        'Interpersonal intelligence' => 'Kecerdasan interpersonal',
        'Intrapersonal intelligence' => 'Kecerdasan intrapersonal',
        'Musical intelligence' => 'Kecerdasan musikal',
        'Naturalist intelligence' => 'Kecerdasan naturalis',
        'Single choice' => 'Pilihan tunggal',
        'True false' => 'Benar salah',
        'Multiple choice' => 'Pilihan ganda',
        'Short answer' => 'Jawaban singkat',
        'Numeric' => 'Numerik',
        'Essay' => 'Esai',
        'Subtopic' => 'Subtopik',
        'Explanation' => 'Penjelasan',
        'Answer key' => 'Kunci jawaban',
        'Optional. Free text grade level, e.g. X or 10.' => 'Opsional. Teks bebas tingkat kelas, mis. X atau 10.',
        'Exam academic context' => 'Konteks akademik ujian',
        'Exam purpose' => 'Tujuan ujian',
        'Grade sync mode' => 'Mode sinkronisasi nilai',
        'Grade sync target' => 'Target sinkronisasi nilai',
        'Runtime exam id' => 'ID ujian runtime',
        'Participant code' => 'Kode peserta',
        'Display name' => 'Nama tampilan',
        'Shuffle questions' => 'Acak soal',
        'Optional. FQCN or slug, e.g. school_class or Modules\\School\\Models\\Student.' => 'Opsional. FQCN atau slug, mis. school_class atau Modules\\School\\Models\\Student.',
        'Optional. Campus component key, e.g. midterm or final.' => 'Opsional. Kunci komponen kampus, mis. midterm atau final.',
        'Exam result' => 'Hasil ujian',
        'Exam schedule' => 'Jadwal ujian',
        'Faculty' => 'Fakultas',
        'Feeder log' => 'Log Feeder',
        'File upload' => 'Unggahan berkas',
        'Finance' => 'Keuangan',
        'Fine' => 'Denda',
        'Global' => 'Global',
        'Goods receipt item' => 'Item penerimaan barang',
        'Goods receipt' => 'Penerimaan barang',
        'Journal entry line' => 'Baris entri jurnal',
        'Journal entry' => 'Entri jurnal',
        'Kpi indicator' => 'Indikator KPI',
        'Kpi score' => 'Nilai KPI',
        'Kpi template' => 'Template KPI',
        'Leave request' => 'Permohonan cuti',
        'Lecturer' => 'Dosen',
        'Library' => 'Perpustakaan',
        'Loan' => 'Peminjaman',
        'Member' => 'Anggota',
        'Module' => 'Modul',
        'Monitoring' => 'Pemantauan',
        'Organization setting' => 'Pengaturan organisasi',
        'Organization' => 'Organisasi',
        'Payment' => 'Pembayaran',
        'Payroll component' => 'Komponen payroll',
        'Position' => 'Jabatan',
        'Procurement category' => 'Kategori pengadaan',
        'Procurement item' => 'Item pengadaan',
        'Procurement' => 'Pengadaan',
        'Province' => 'Provinsi',
        'Purchase order item' => 'Item pesanan pembelian',
        'Purchase order' => 'Pesanan pembelian',
        'Purchase requisition item' => 'Item permintaan pembelian',
        'Purchase requisition' => 'Permintaan pembelian',
        'Registration' => 'Registrasi',
        'Request for quotation' => 'Permintaan penawaran',
        'Rfq item' => 'Item RFQ',
        'Rfq vendor' => 'Vendor RFQ',
        'Salary slip component' => 'Komponen slip gaji',
        'Salary slip' => 'Slip gaji',
        'Schedule' => 'Jadwal',
        'School class' => 'Kelas',
        'School' => 'Sekolah',
        'Shift' => 'Shift',
        'Student achievement' => 'Prestasi siswa',
        'Student assessment answer' => 'Jawaban asesmen siswa',
        'Student grade' => 'Nilai siswa',
        'Student invoice item' => 'Item tagihan siswa',
        'Student invoice' => 'Tagihan siswa',
        'Student' => 'Siswa',
        'Student report card' => 'Rapor Siswa',
        'Study plan item' => 'Item rencana studi',
        'Study plan' => 'Rencana studi',
        'Study program' => 'Program studi',
        'Study result' => 'Hasil studi',
        'Subject' => 'Mata pelajaran',
        'Subscription log' => 'Riwayat langganan',
        'Teacher' => 'Guru',
        'Tenant module' => 'Modul tenant',
        'Tenant role' => 'Peran tenant',
        'Tenant setting' => 'Pengaturan tenant',
        'Tenant' => 'Tenant',
        'Thesis' => 'Tesis',
        'Timezone' => 'Zona waktu',
        'Tuition type' => 'Jenis biaya pendidikan',
        'User tenant role' => 'Peran pengguna tenant',
        'User' => 'Pengguna',
        'Vendor bill item' => 'Item tagihan vendor',
        'Vendor bill' => 'Tagihan vendor',
        'Vendor' => 'Vendor',
        'Village' => 'Desa',
        'Violation type' => 'Jenis pelanggaran',
        'Violation' => 'Pelanggaran',
        'Executive' => 'Eksekutif',
        'Reports' => 'Laporan',
        'Export Center' => 'Pusat Ekspor',
        'Cost efficiency' => 'Efisiensi biaya',
        'Revenue trend' => 'Tren pendapatan',
        'Payroll trend' => 'Tren penggajian',
        'Outstanding AR vs AP' => 'Piutang vs hutang outstanding',
        'Pending approvals trend' => 'Tren persetujuan tertunda',
        'Revenue MTD' => 'Pendapatan MTD',
        'Payroll MTD' => 'Penggajian MTD',
        'Outstanding AP' => 'Hutang outstanding',
        'Outstanding AR' => 'Piutang outstanding',
        'Active Tenants' => 'Tenant aktif',
        'Pending Approvals' => 'Persetujuan tertunda',
        'Security Events' => 'Kejadian keamanan',
        'Value diff' => 'Perbandingan nilai',
        'General' => 'Umum',
        'Generate report' => 'Buat laporan',
        'Last 7 days' => '7 hari terakhir',
        'Last 30 days' => '30 hari terakhir',
        'Last 90 days' => '90 hari terakhir',
        'Efficiency ratio' => 'Rasio efisiensi',
        'Re-download' => 'Unduh ulang',
        'Retry failed' => 'Coba lagi yang gagal',
        'Retry sync' => 'Coba sinkron ulang',
        'Retry selected' => 'Coba ulang yang dipilih',
        'Moodle sync queued' => 'Sinkron Moodle masuk antrean',
        'Outbox details' => 'Detail outbox',
        'Pending' => 'Menunggu',
        'Processing' => 'Memproses',
        'Synced' => 'Tersinkron',
        'Failed' => 'Gagal',
        'In progress' => 'Sedang diproses',
        'Successful rows' => 'Baris berhasil',
        'Total rows' => 'Total baris',
        'Verified payments this month' => 'Pembayaran terverifikasi bulan ini',
        'Approved and paid salary slips' => 'Slip gaji disetujui dan dibayar',
        'Vendor bills not fully paid' => 'Tagihan vendor belum lunas',
        'Student invoices outstanding' => 'Tagihan siswa belum lunas',
        'Active SaaS accounts' => 'Akun SaaS aktif',
        'Workflow instances in progress' => 'Instans workflow berjalan',

        // ── Plural forms (Filament auto-generates plural for navigation labels) ─
        'Academic periods' => 'Periode Akademik',
        'Academic years' => 'Tahun Akademik',
        'Achievement types' => 'Jenis Prestasi',
        'Admission periods' => 'Periode Penerimaan',
        'Assessment items' => 'Item Asesmen',
        'Assessments' => 'Asesmen',
        'Attendance logs' => 'Log Kehadiran',
        'Attendances' => 'Absensi',
        'Audit logs' => 'Log Audit',
        'Book categories' => 'Kategori Buku',
        'Book copies' => 'Eksemplar Buku',
        'Books' => 'Buku',
        'Budgets' => 'Anggaran',
        'Chart of accounts' => 'Bagan Akun',
        'Customer invoices' => 'Invoice Pelanggan',
        'Customer invoice items' => 'Item Invoice Pelanggan',
        'Cities' => 'Kota',
        'Class students' => 'Siswa Kelas',
        'Collage students' => 'Mahasiswa',
        'Countries' => 'Negara',
        'Course offerings' => 'Penawaran Mata Kuliah',
        'Courses' => 'Mata Kuliah',
        'Curricula' => 'Kurikulum',
        'Departments' => 'Departemen',
        'Districts' => 'Kecamatan',
        'Employees' => 'Karyawan',
        'Employment contracts' => 'Kontrak Kerja',
        'Exam schedules' => 'Jadwal Ujian',
        'Faculties' => 'Fakultas',
        'Feeder logs' => 'Log Feeder',
        'File uploads' => 'Unggahan Berkas',
        'Fines' => 'Denda',
        'Goods receipt items' => 'Item Penerimaan Barang',
        'Goods receipts' => 'Penerimaan Barang',
        'Journal entries' => 'Entri Jurnal',
        'Journal entry lines' => 'Baris Entri Jurnal',
        'Kpi indicators' => 'Indikator KPI',
        'Kpi scores' => 'Nilai KPI',
        'Kpi templates' => 'Template KPI',
        'Leave requests' => 'Permohonan Cuti',
        'Lecturers' => 'Dosen',
        'Loans' => 'Peminjaman',
        'Members' => 'Anggota',
        'Modules' => 'Modul',
        'Organization settings' => 'Pengaturan Organisasi',
        'Organizations' => 'Organisasi',
        'Payments' => 'Pembayaran',
        'Payroll components' => 'Komponen Payroll',
        'Positions' => 'Jabatan',
        'Procurement categories' => 'Kategori Pengadaan',
        'Procurement items' => 'Item Pengadaan',
        'Provinces' => 'Provinsi',
        'Purchase order items' => 'Item Pesanan Pembelian',
        'Purchase orders' => 'Pesanan Pembelian',
        'Purchase requisition items' => 'Item Permintaan Pembelian',
        'Purchase requisitions' => 'Permintaan Pembelian',
        'Registrations' => 'Registrasi',
        'Request for quotations' => 'Permintaan Penawaran',
        'Rfq items' => 'Item RFQ',
        'Rfq vendors' => 'Vendor RFQ',
        'Salary slip components' => 'Komponen Slip Gaji',
        'Salary slips' => 'Slip Gaji',
        'Schedules' => 'Jadwal',
        'School classes' => 'Kelas',
        'Shifts' => 'Shift',
        'Student achievements' => 'Prestasi Siswa',
        'Student assessment answers' => 'Jawaban Asesmen Siswa',
        'Student grades' => 'Nilai Siswa',
        'Student invoice items' => 'Item Tagihan Siswa',
        'Student invoices' => 'Tagihan Siswa',
        'Students' => 'Siswa',
        'Study plan items' => 'Item Rencana Studi',
        'Study plans' => 'Rencana Studi',
        'Study programs' => 'Program Studi',
        'Study results' => 'Hasil Studi',
        'Subjects' => 'Mata Pelajaran',
        'Subscription logs' => 'Riwayat Langganan',
        'Subscription plans' => 'Paket Langganan',
        'Teachers' => 'Guru',
        'Tenant modules' => 'Modul Tenant',
        'Tenant roles' => 'Peran Tenant',
        'Tenant settings' => 'Pengaturan Tenant',
        'Tenants' => 'Tenant',
        'Theses' => 'Tesis',
        'Timezones' => 'Zona Waktu',
        'Tuition types' => 'Jenis Biaya Pendidikan',
        'User tenant roles' => 'Peran Pengguna Tenant',
        'Users' => 'Pengguna',
        'Vendor bill items' => 'Item Tagihan Vendor',
        'Vendor bills' => 'Tagihan Vendor',
        'Vendors' => 'Vendor',
        'Villages' => 'Desa',
        'Violation types' => 'Jenis Pelanggaran',
        'Violations' => 'Pelanggaran',

        // ── Specific field/relation labels ──────────────────────────────────────
        'Academic advisor' => 'Dosen Pembimbing', // field: academicAdvisor
        'Student number' => 'NIM',
        'National student number' => 'NISN/NIM Nasional',
        'Full name' => 'Nama Lengkap',
        'Entry year' => 'Tahun Masuk',
        'Entry semester' => 'Semester Masuk',
        'Admission type' => 'Jalur Masuk',
        'Current semester' => 'Semester Saat Ini',
        'Graduation date' => 'Tanggal Lulus',
        'Created at' => 'Dibuat pada',
        'Updated at' => 'Diperbarui pada',
        'Email address' => 'Alamat Email',
        'Is active' => 'Aktif',
        'Is locked' => 'Dikunci',
        'Start date' => 'Tanggal mulai',
        'End date' => 'Tanggal selesai',

        // ── Fase 1.2 — tambahan frasa audit 2026-05-22 ──────────────────────────
        'Phone number' => 'Nomor telepon',
        'Started at' => 'Dimulai pada',
        'Finished at' => 'Selesai pada',
        'Due at' => 'Jatuh tempo',
        'Published at' => 'Dipublikasikan pada',
        'Birth date' => 'Tanggal lahir',
        'Birth place' => 'Tempat lahir',
        'Father name' => 'Nama ayah',
        'Mother name' => 'Nama ibu',
        'Quantity' => 'Jumlah',
        'Unit price' => 'Harga satuan',
        'Total amount' => 'Total',
        'Profit & Loss' => 'Laba Rugi',
        'Balance Sheet' => 'Neraca',
        'Cash Flow' => 'Arus Kas',
        'Revenue' => 'Pendapatan',
        'Expenses' => 'Beban',
        'Net Income' => 'Laba/Rugi Bersih',
        'Net Cash' => 'Kas Bersih',
        'Assets' => 'Aset',
        'Liabilities' => 'Liabilitas',
        'Equity' => 'Ekuitas',
        'As Of Date' => 'Per Tanggal',
        'As Of' => 'Per',
        'Filter Period' => 'Filter Periode',
        'Filter' => 'Filter',
        'Total Revenue' => 'Total Pendapatan',
        'Total Expenses' => 'Total Beban',
        'Total Assets' => 'Total Aset',
        'Total Liabilities' => 'Total Liabilitas',
        'Total Equity' => 'Total Ekuitas',
        'Operating Activities' => 'Aktivitas Operasional',
        'Investing Activities' => 'Aktivitas Investasi',
        'Financing Activities' => 'Aktivitas Pendanaan',
        'Balance sheet is not balanced!' => 'Neraca tidak seimbang!',
        'From' => 'Dari',
        'To' => 'Sampai',
        'Export PDF' => 'Ekspor PDF',
        'All Organizations' => 'Semua Organisasi',
        'Calculate Payroll' => 'Hitung Payroll',
        'Payroll calculated.' => 'Payroll berhasil dihitung.',
        'Salary slip marked as paid.' => 'Slip gaji ditandai lunas.',
        'Download PDF' => 'Unduh PDF',
        'Download bulk PDF' => 'Unduh PDF massal',
        'Class grade ledger' => 'Buku nilai kelas',
        'Approve Slip' => 'Setujui Slip',
        'Mark as Paid' => 'Tandai Lunas',
        'Paid At' => 'Dibayar Pada',
        'Paid Via' => 'Dibayar Via',
        'Send to Employee' => 'Kirim ke Karyawan',
        'Verify' => 'Verifikasi',
        'e.g. NIK, NPWP number' => 'Contoh: NIK, Nomor NPWP',
        'Unverified' => 'Belum Diverifikasi',
        'Verified' => 'Terverifikasi',
        'Expired' => 'Kadaluarsa',
        'Click to auto-detect' => 'Klik untuk deteksi otomatis',
        'Check-In Latitude' => 'Lintang Check-In',
        'Check-In Longitude' => 'Bujur Check-In',
        'Check-Out Latitude' => 'Lintang Check-Out',
        'Check-Out Longitude' => 'Bujur Check-Out',
        'Accuracy (m)' => 'Akurasi (m)',
        'Capture GPS coordinates via the browser geolocation API.' => 'Tangkap koordinat GPS melalui API geolokasi browser.',
        'Present' => 'Hadir',
        'Late' => 'Terlambat',
        'Leave' => 'Cuti',
        'Holiday' => 'Libur',
        'hours' => 'jam',
        'Sub total' => 'Subtotal',
        'Tax' => 'Pajak',
        'Discount' => 'Diskon',
        'Reference number' => 'Nomor referensi',
        'Reference' => 'Referensi',
        'Remarks' => 'Catatan',
        'Notes' => 'Catatan',
        'Description' => 'Deskripsi',
        'Status' => 'Status',
        'General information' => 'Informasi umum',
        'Settings' => 'Pengaturan',
        'Scope' => 'Cakupan',
        'Configuration' => 'Konfigurasi',
        'Approval' => 'Persetujuan',
        'Trigger event' => 'Event pemicu',
        'Trigger mode' => 'Mode pemicu',
        'Subject type' => 'Tipe subjek',
        'Subject label' => 'Label subjek',
        'Step' => 'Langkah',
        'Steps' => 'Langkah',
        'Action type' => 'Jenis aksi',
        'Sort order' => 'Urutan',
        'Version' => 'Versi',
        'Current step' => 'Langkah saat ini',
        'Requester' => 'Pemohon',
        'Status before' => 'Status sebelum',
        'Status after' => 'Status sesudah',
        'Workflow version' => 'Versi workflow',
        'Step type' => 'Tipe langkah',
        'To step' => 'Ke langkah',
        'Sla hours' => 'Batas waktu (jam)',
        'Calculation' => 'Kalkulasi',
        'Payment details' => 'Detail pembayaran',
        'Payment method' => 'Metode pembayaran',
        'Loan limits' => 'Batas peminjaman',
        'Quantity and pricing' => 'Jumlah & harga',
        'Is taxable' => 'Kena pajak',
        'Is mandatory' => 'Wajib',
        'Created by' => 'Dibuat oleh',
        'Updated by' => 'Diperbarui oleh',
        'Preferred locale' => 'Bahasa',
        'Language' => 'Bahasa',
        // Collage student typo dipertahankan — alias UI; jangan rename tanpa rename file Resource

        // ── Sprint 2 — Workflow-specific phrases ────────────────────────────────
        'Workflow' => 'Workflow',
        'Workflow instance' => 'Instans workflow',
        'Workflow step' => 'Langkah workflow',
        'Workflow transition' => 'Transisi workflow',
        'Workflow instances' => 'Instans Workflow',
        'Workflow steps' => 'Langkah Workflow',
        'Workflow transitions' => 'Transisi Workflow',
        'Workflow snapshot' => 'Snapshot workflow',
        'Automated actions' => 'Aksi otomatis',
        'Automated action' => 'Aksi otomatis',
        'From step' => 'Dari langkah',
        'Action name' => 'Nama aksi',
        'Assignee type' => 'Tipe penerima',
        'Assignee value' => 'Nilai penerima',
        'Assignee config' => 'Konfigurasi penerima',
        'Is initial' => 'Langkah awal',
        'Is terminal' => 'Langkah akhir',
        'Allow reassign' => 'Izinkan reassign',
        'Allow delegate' => 'Izinkan delegasi',
        'Form schema' => 'Skema form',
        'Action schema' => 'Skema aksi',
        'Accepted types' => 'Tipe yang diizinkan',
        'Max size' => 'Ukuran maksimum',
        'Condition rules' => 'Aturan kondisi',
        'Rule type' => 'Jenis aturan',
        'Transition meta' => 'Meta transisi',
        'Is default' => 'Default',
        'Is global' => 'Global',
        'Is published' => 'Dipublikasikan',
        'Context data' => 'Data konteks',
        'Form data' => 'Data form',
        'Computed data' => 'Data terkomputasi',
        'Current assignees' => 'Penerima saat ini',
        'Completed at' => 'Selesai pada',
        'Request number' => 'Nomor permintaan',
        'Budget code' => 'Kode anggaran',
        'Requested amount' => 'Jumlah diminta',
        'Allocated amount' => 'Jumlah dialokasikan',
        'Assignment role' => 'Peran penugasan',
        'Assigned at' => 'Ditugaskan pada',
        'Assigned to type' => 'Tipe penerima tugas',
        'Assigned user' => 'Pengguna ditugaskan',
        'Log type' => 'Tipe log',
        'Logged at' => 'Dicatat pada',
        'Action taken' => 'Aksi diambil',
        'Actor' => 'Pelaku',
        'Payload before' => 'Payload sebelum',
        'Payload after' => 'Payload sesudah',
        'Form data snapshot' => 'Snapshot data form',
        'Priority' => 'Prioritas',
        'Leave blank for tenant-wide workflow' => 'Kosongkan untuk workflow tenant-wide',
        'Enter the FQCN of the subject model' => 'Isi FQCN model subject',
        'Use valid JsonLogic format' => 'Gunakan format JsonLogic yang valid',
        'Reason for reassignment' => 'Alasan pemindahan',
        'Reassign' => 'Pindahkan',
        'Target user' => 'Pengguna tujuan',
        'Publish' => 'Publikasikan',
        'Archive' => 'Arsipkan',
        'Duplicate as New Version' => 'Duplikat sebagai Versi Baru',
        'Open Subject' => 'Buka Subjek',
        'Return To Step' => 'Kembalikan ke Langkah',
        'Target Step' => 'Langkah Tujuan',
        'Workflow Note' => 'Catatan Workflow',
        'Open Active Workflow' => 'Buka Workflow Aktif',
        'Start Approval Workflow' => 'Mulai Workflow Persetujuan',
        'Approval workflow started.' => 'Workflow persetujuan dimulai.',
        'Unable to start approval workflow.' => 'Tidak dapat memulai workflow persetujuan.',
        'Budget approval workflow started.' => 'Workflow persetujuan anggaran dimulai.',
        'Unable to start budget approval workflow.' => 'Tidak dapat memulai workflow persetujuan anggaran.',
        'Draft' => 'Draf',
        'In Review' => 'Dalam Review',
        'Approved' => 'Disetujui',
        'Rejected' => 'Ditolak',
        'Total Books' => 'Total Buku',
        'All books in the catalog' => 'Semua buku di katalog',
        'Books on Loan' => 'Buku Dipinjam',
        'Currently borrowed' => 'Sedang dipinjam',
        'Overdue Loans' => 'Peminjaman Terlambat',
        'Past due date' => 'Melewati tanggal jatuh tempo',
        'Active Members' => 'Anggota Aktif',
        'Members in good standing' => 'Anggota dengan status baik',

        // ── Sprint 3 — Section / Tab / Fieldset titles ────────────────────────────
        'Basic information' => 'Informasi dasar',
        'Basic info' => 'Informasi dasar',
        'Academic information' => 'Informasi akademik',
        'Academic details' => 'Informasi akademik',
        'Academic affiliation' => 'Afiliasi akademik',
        'Academic position' => 'Posisi akademik',
        'Academic progress' => 'Kemajuan akademik',
        'Academic registration' => 'Registrasi akademik',
        'Address details' => 'Detail alamat',
        'Address & contact' => 'Alamat & kontak',
        'Contact details' => 'Detail kontak',
        'Parent contact' => 'Kontak orang tua',
        'Enrollment details' => 'Detail pendaftaran',
        'Timestamps' => 'Waktu',
        'Status & timestamps' => 'Status & waktu',
        'Status & approval' => 'Status & persetujuan',
        'Status & notes' => 'Status & catatan',
        'Status & settings' => 'Status & pengaturan',
        'Status & period' => 'Status & periode',
        'Status & location' => 'Status & lokasi',
        'Identity' => 'Identitas',
        'Student identity' => 'Identitas siswa',
        'Scope & identity' => 'Cakupan & identitas',
        'Scope & category' => 'Cakupan & kategori',
        'Personal information' => 'Informasi pribadi',
        'Health & physical' => 'Kesehatan & fisik',
        'Classification' => 'Klasifikasi',
        'Classification & physical details' => 'Klasifikasi & detail fisik',
        'Classification & scoring' => 'Klasifikasi & penilaian',
        'Classification & status' => 'Klasifikasi & status',
        'Teacher details' => 'Detail guru',
        'Teachers & capacity' => 'Guru & kapasitas',
        'Class details' => 'Detail kelas',
        'Schedule details' => 'Detail jadwal',
        'Schedule & location' => 'Jadwal & lokasi',
        'Schedule time' => 'Waktu jadwal',
        'Time & location' => 'Waktu & lokasi',
        'Timeline' => 'Linimasa',
        'Timeline & notes' => 'Linimasa & catatan',
        'Scoring' => 'Penilaian',
        'Achievement details' => 'Detail prestasi',
        'Violation information' => 'Informasi pelanggaran',
        'Sanctions & resolution' => 'Sanksi & penyelesaian',
        'Reporting' => 'Pelaporan',
        'Reporting & handling' => 'Pelaporan & penanganan',
        'Category details' => 'Detail kategori',
        'Category information' => 'Informasi kategori',
        'Certification & education' => 'Sertifikasi & pendidikan',
        'Certificate & media' => 'Sertifikat & media',
        'Thesis details' => 'Detail tesis',
        'Library policy' => 'Kebijakan perpustakaan',
        'Loan details' => 'Detail peminjaman',
        'Fine details' => 'Detail denda',
        'Activity & fines' => 'Aktivitas & denda',
        'Reservation' => 'Reservasi',
        'Acquisition' => 'Akuisisi',
        'Stock take' => 'Stok opname',
        'Specifications' => 'Spesifikasi',
        'Physical details' => 'Detail fisik',
        'Branding' => 'Branding',
        'Appearance' => 'Tampilan',
        'Vendor details' => 'Detail vendor',
        'Banking' => 'Perbankan',
        'Blacklist reason' => 'Alasan daftar hitam',
        'Rejection reason' => 'Alasan penolakan',
        'Terms & notes' => 'Syarat & catatan',
        'Quantity & budget' => 'Jumlah & anggaran',
        'Quantity & pricing' => 'Jumlah & harga',
        'Budget & status' => 'Anggaran & status',
        'Budget account' => 'Akun anggaran',
        'Bill details' => 'Detail tagihan',
        'Receipt information' => 'Informasi penerimaan',
        'Attempt information' => 'Informasi percobaan',
        'Requirements & criteria' => 'Persyaratan & kriteria',
        'Recurrence & notes' => 'Pengulangan & catatan',
        'Residence & transport' => 'Tempat tinggal & transportasi',
        'Authentication' => 'Autentikasi',
        'Relationships' => 'Relasi',
        'Additional' => 'Tambahan',
        'Serial' => 'Serial',
        'References' => 'Referensi',
        'Capacity & status' => 'Kapasitas & status',
        'Authors' => 'Penulis',
        'Authors (master data)' => 'Penulis (master data)',
        'Subjects (master data)' => 'Mata pelajaran (master data)',
        'Bill information' => 'Informasi tagihan',
        'Order details' => 'Detail pesanan',
        'Supplier details' => 'Detail pemasok',
        'Delivery details' => 'Detail pengiriman',
        'Approval information' => 'Informasi persetujuan',

        // ── Sprint 4 — Helper text & placeholder phrases ──────────────────────────
        'Optional. Leave blank for tenant-wide data.' => 'Opsional. Kosongkan untuk data tenant-wide.',
        'Optional. Leave blank for tenant-wide stock takes.' => 'Opsional. Kosongkan untuk stock take tenant-wide.',
        'Optional. Leave blank for tenant-wide fines.' => 'Opsional. Kosongkan untuk denda tenant-wide.',
        'Optional. Leave blank for tenant-wide members.' => 'Opsional. Kosongkan untuk member tenant-wide (lintas organisasi).',
        'Optional. Leave blank for tenant-wide transactions.' => 'Opsional. Kosongkan untuk transaksi tenant-wide.',
        'Optional. Leave blank for tenant-wide copies.' => 'Opsional. Kosongkan untuk copy tenant-wide.',
        'Leave blank for tenant-wide policy.' => 'Kosongkan agar policy berlaku tenant-wide.',
        'Leave blank for the tenant-wide library policy.' => 'Kosongkan untuk kebijakan perpustakaan tenant-wide (terpusat).',
        'Leave blank for tenant-wide categories.' => 'Kosongkan untuk kategori tenant-wide (terpusat).',
        'Optional. If filled, publisher name follows master data.' => 'Opsional. Jika diisi, nama penerbit akan mengikuti master data.',
        'Optional. Select authors from master data for report consistency.' => 'Opsional. Pilih penulis dari master data untuk konsistensi laporan.',
        'Optional. Select topics for report classification.' => 'Opsional. Pilih topik/subject untuk klasifikasi laporan.',
        'Optional. If filled, loan policy follows member type.' => 'Opsional. Jika diisi, kebijakan peminjaman mengikuti tipe member.',
        'Optional. Fill if location is not registered in master data.' => 'Opsional. Isi jika lokasi belum terdaftar di master data.',
        'Separate authors with commas.' => 'Pisahkan penulis dengan koma.',
        'Separate keywords with commas.' => 'Pisahkan kata kunci dengan koma.',
        'Fill if this title is a serial or journal.' => 'Isi jika judul ini berjenis serial/jurnal.',
        'General Material Designation (GMD).' => 'General Material Designation (GMD).',
        'Note for this action (optional).' => 'Catatan aksi ini (opsional).',
        // ── ROADMAP v04 — Parent portal & messaging ───────────────────────────────
        'Parent portal' => 'Portal orang tua',
        'My children' => 'Anak saya',
        'Child' => 'Anak',
        'Foundation structure' => 'Struktur yayasan',
        'Helpdesk dashboard' => 'Dasbor helpdesk',
        'Sustainability dashboard' => 'Dasbor keberlanjutan',
        'Visitor kiosk' => 'Kiosk pengunjung',
        'Visitor checked in' => 'Pengunjung berhasil check-in',
        'Check in' => 'Check-in',
        'Open tickets' => 'Tiket terbuka',
        'Escalated tickets' => 'Tiket eskalasi',
        'Average resolution hours' => 'Rata-rata jam penyelesaian',
        'Estimated carbon footprint (kg CO2e)' => 'Estimasi jejak karbon (kg CO2e)',
        'No organizations found' => 'Tidak ada organisasi ditemukan',
    ];

    /**
     * Word-by-word translations used as a fallback when a phrase is not in the map.
     *
     * @var array<string, string>
     */
    protected const WORDS = [
        'academic' => 'akademik',
        'accreditation' => 'akreditasi',
        'account' => 'akun',
        'achievement' => 'prestasi',
        'admission' => 'penerimaan',
        'address' => 'alamat',
        'advisor' => 'pembimbing',
        'allow' => 'izinkan',
        'amount' => 'jumlah',
        'anonymous' => 'anonim',
        'applicant' => 'pendaftar',
        'assessment' => 'asesmen',
        'assistant' => 'asisten',
        'attendance' => 'kehadiran',
        'author' => 'penulis',
        'available' => 'tersedia',
        'average' => 'rata-rata',
        'award' => 'penghargaan',
        'bank' => 'bank',
        'billing' => 'penagihan',
        'month' => 'bulan',
        'book' => 'buku',
        'brand' => 'merek',
        'budget' => 'anggaran',
        'category' => 'kategori',
        'certificate' => 'sertifikat',
        'chart' => 'bagan',
        'class' => 'kelas',
        'code' => 'kode',
        'collage' => 'perguruan tinggi',
        'color' => 'warna',
        'component' => 'komponen',
        'contact' => 'kontak',
        'contract' => 'kontrak',
        'country' => 'negara',
        'course' => 'mata kuliah',
        'created' => 'dibuat',
        'currency' => 'mata uang',
        'current' => 'saat ini',
        'curriculum' => 'kurikulum',
        'date' => 'tanggal',
        'day' => 'hari',
        'department' => 'departemen',
        'description' => 'deskripsi',
        'district' => 'kecamatan',
        'document' => 'dokumen',
        'due' => 'jatuh tempo',
        'duration' => 'durasi',
        'education' => 'pendidikan',
        'email' => 'email',
        'employee' => 'karyawan',
        'employment' => 'kepegawaian',
        'end' => 'akhir',
        'entry' => 'entri',
        'exam' => 'ujian',
        'expense' => 'beban',
        'faculty' => 'fakultas',
        'feeder' => 'Feeder',
        'file' => 'berkas',
        'finance' => 'keuangan',
        'first' => 'pertama',
        'frequency' => 'frekuensi',
        'full' => 'lengkap',
        'gender' => 'jenis kelamin',
        'grade' => 'nilai',
        'graduation' => 'kelulusan',
        'guardian' => 'wali',
        'handled' => 'ditangani',
        'health' => 'kesehatan',
        'history' => 'riwayat',
        'id' => 'ID',
        'indicator' => 'indikator',
        'invoice' => 'tagihan',
        'is' => 'status',
        'journal' => 'jurnal',
        'job' => 'pekerjaan',
        'kpi' => 'KPI',
        'language' => 'bahasa',
        'leave' => 'cuti',
        'level' => 'level',
        'lecturer' => 'dosen',
        'library' => 'perpustakaan',
        'loan' => 'peminjaman',
        'log' => 'log',
        'logo' => 'logo',
        'main' => 'utama',
        'member' => 'anggota',
        'module' => 'modul',
        'mother' => 'ibu',
        'name' => 'nama',
        'national' => 'nasional',
        'number' => 'nomor',
        'offering' => 'penawaran',
        'organization' => 'organisasi',
        'parent' => 'induk',
        'payment' => 'pembayaran',
        'period' => 'periode',
        'phone' => 'telepon',
        'plan' => 'rencana',
        'position' => 'jabatan',
        'previous' => 'sebelumnya',
        'principal' => 'kepala',
        'procurement' => 'pengadaan',
        'program' => 'program',
        'province' => 'provinsi',
        'purchase' => 'pembelian',
        'question' => 'pertanyaan',
        'quotation' => 'penawaran',
        'receipt' => 'penerimaan',
        'registration' => 'registrasi',
        'related' => 'terkait',
        'report' => 'laporan',
        'required' => 'wajib',
        'result' => 'hasil',
        'role' => 'peran',
        'route' => 'rute',
        'salary' => 'gaji',
        'schedule' => 'jadwal',
        'school' => 'sekolah',
        'score' => 'nilai',
        'secondary' => 'sekunder',
        'semester' => 'semester',
        'setting' => 'pengaturan',
        'shift' => 'shift',
        'slip' => 'slip',
        'student' => 'siswa',
        'study' => 'studi',
        'subject' => 'mata pelajaran',
        'subscription' => 'langganan',
        'teacher' => 'guru',
        'tenant' => 'tenant',
        'template' => 'template',
        'thesis' => 'tesis',
        'time' => 'waktu',
        'timezone' => 'zona waktu',
        'title' => 'judul',
        'total' => 'total',
        'type' => 'jenis',
        'updated' => 'diperbarui',
        'user' => 'pengguna',
        'vendor' => 'vendor',
        'village' => 'desa',
        'violation' => 'pelanggaran',
        'week' => 'minggu',
        'year' => 'tahun',

        // Fase 1.2 — tambahan kata audit 2026-05-22
        'started' => 'dimulai',
        'finished' => 'selesai',
        'published' => 'dipublikasikan',
        'remarks' => 'catatan',
        'phase' => 'fase',
        'cycle' => 'siklus',
        'mode' => 'mode',
        'gateway' => 'gerbang',
        'quorum' => 'kuorum',
        'assignee' => 'penanggung jawab',
        'approver' => 'penyetuju',
        'reviewer' => 'peninjau',
        'outcome' => 'hasil',
        'branch' => 'cabang',
        'instance' => 'instans',
        'preferred' => 'disukai',
        'locale' => 'bahasa',
        'sla' => 'SLA',
        'rfq' => 'RFQ',
        'tax' => 'pajak',
        'discount' => 'diskon',
        'quantity' => 'jumlah',
        'calculation' => 'kalkulasi',
        'approval' => 'persetujuan',
        'requester' => 'pemohon',
        'version' => 'versi',

        // Sprint 2 — Workflow words
        'from' => 'dari',
        'to' => 'ke',
        'rule' => 'aturan',
        'condition' => 'kondisi',
        'trigger' => 'pemicu',
        'transition' => 'transisi',
        'context' => 'konteks',
        'computed' => 'terkomputasi',
        'snapshot' => 'snapshot',
        'actor' => 'pelaku',
        'payload' => 'payload',
        'priority' => 'prioritas',
        'schema' => 'skema',
        'initial' => 'awal',
        'terminal' => 'akhir',
        'delegate' => 'delegasi',
        'reassign' => 'pindahkan',
        'target' => 'tujuan',
        'logged' => 'dicatat',
        'completed' => 'selesai',
        'assigned' => 'ditugaskan',
        'allocation' => 'alokasi',
        'allocated' => 'dialokasikan',
        'request' => 'permintaan',
        'requested' => 'diminta',

        // Sprint 3 — section title words
        'affiliation' => 'afiliasi',
        'authentication' => 'autentikasi',
        'classification' => 'klasifikasi',
        'enrollment' => 'pendaftaran',
        'identity' => 'identitas',
        'physical' => 'fisik',
        'personal' => 'pribadi',
        'residence' => 'tempat tinggal',
        'transport' => 'transportasi',
        'sanctions' => 'sanksi',
        'resolution' => 'penyelesaian',
        'criteria' => 'kriteria',
        'recurrence' => 'pengulangan',
        'specifications' => 'spesifikasi',
        'branding' => 'branding',
        'appearance' => 'tampilan',
        'banking' => 'perbankan',
        'acquisition' => 'akuisisi',
        'reservation' => 'reservasi',
        'timeline' => 'linimasa',
        'timestamps' => 'waktu',
        'capacity' => 'kapasitas',
        'handling' => 'penanganan',
        'scoring' => 'penilaian',
        'additional' => 'tambahan',
        'serial' => 'serial',
        'delivery' => 'pengiriman',
        'supplier' => 'pemasok',
        'detail' => 'detail',
        'details' => 'detail',
    ];

    public static function text(string $value): string
    {
        if (! static::isIndonesian()) {
            return $value;
        }

        $normalized = str($value)->replace(['_', '.'], ' ')->squish()->toString();
        $lowercaseFirst = ucfirst(strtolower($normalized));

        // 1. Try file-based translation first
        $fileTranslation = static::resolveFromFile($value, $normalized, $lowercaseFirst);
        if ($fileTranslation !== null) {
            return $fileTranslation;
        }

        // 2. Fall back to hardcoded PHRASES
        if (array_key_exists($value, static::PHRASES)) {
            return static::PHRASES[$value];
        }

        if (array_key_exists($normalized, static::PHRASES)) {
            return static::PHRASES[$normalized];
        }

        // Case-insensitive lookup: 'Study Program' should match 'Study program'
        if (array_key_exists($lowercaseFirst, static::PHRASES)) {
            return static::PHRASES[$lowercaseFirst];
        }

        $translated = collect(preg_split('/(\s+)/', $normalized, -1, PREG_SPLIT_DELIM_CAPTURE) ?: [])
            ->map(function (string $token): string {
                if (trim($token) === '') {
                    return $token;
                }

                if (preg_match('/^\s+$/', $token)) {
                    return $token;
                }

                return static::translateWord($token);
            })
            ->implode('');

        return trim($translated);
    }

    protected static function resolveFromFile(string $value, string $normalized, string $lowercaseFirst): ?string
    {
        // Try caller module first
        if ($module = static::getCallerModule()) {
            $lowerModule = strtolower($module);

            foreach ([$value, $normalized, $lowercaseFirst] as $key) {
                $translationKey = "{$lowerModule}::{$lowerModule}.{$key}";
                if (app('translator')->has($translationKey)) {
                    return __($translationKey);
                }
            }
        }

        // Fall back to core module
        foreach ([$value, $normalized, $lowercaseFirst] as $key) {
            $translationKey = "core::core.{$key}";
            if (app('translator')->has($translationKey)) {
                return __($translationKey);
            }
        }

        return null;
    }

    protected static function getCallerModule(): ?string
    {
        $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 10);
        foreach ($trace as $step) {
            if (isset($step['class'])) {
                $class = $step['class'];
                if (str_starts_with($class, 'Modules\\')) {
                    return str($class)->after('Modules\\')->before('\\')->toString();
                }
            }
        }

        return null;
    }

    public static function field(string $field): string
    {
        $isDottedRelation = str_contains($field, '.');

        $label = str($field)
            ->beforeLast('_id')              // strip FK suffix first
            ->replace('_', ' ')              // snake_case → spaces
            ->replace('.', ' ')              // dot notation → spaces
            ->replaceMatches('/([a-z])([A-Z])/', '$1 $2')  // camelCase → spaces
            ->squish()
            ->toString();

        // Only strip trailing ' name', ' id', ' code' for dotted relation columns
        // like 'studyProgram.name' → 'study program name' → 'study program'
        // But NOT for plain fields like 'full_name' or 'first_name'
        if ($isDottedRelation) {
            $label = preg_replace('/\s+(name|id|code)$/i', '', $label) ?? $label;
        }

        if ($label === '') {
            $label = $field;
        }

        return static::text(Str::headline($label));
    }

    public static function resource(string $modelClass): string
    {
        $basename = class_basename($modelClass);
        $basename = str($basename)->beforeLast('Resource')->toString();

        return static::text(Str::headline($basename));
    }

    public static function resourceIcon(string $modelClass): string|UnitEnum
    {
        $basename = class_basename($modelClass);
        $basename = str($basename)->beforeLast('Resource')->toString();

        return match ($basename) {
            'AcademicPeriod', 'AcademicYear', 'AdmissionPeriod', 'Schedule', 'ExamSchedule', 'CourseOffering', 'Attendance', 'AttendanceLog', 'Shift' => Heroicon::CalendarDays,
            'AchievementType', 'Assessment', 'AssessmentItem', 'StudentAchievement', 'StudentAssessmentAnswer', 'StudentGrade', 'StudyResult', 'KpiIndicator', 'KpiScore', 'Violation', 'ViolationType' => Heroicon::ChartBar,
            'Applicant', 'Registration' => Heroicon::ClipboardDocumentCheck,
            'AuditLog', 'FileUpload', 'Monitoring' => Heroicon::ShieldCheck,
            'Book', 'BookCategory', 'BookCopy', 'Fine', 'Loan', 'Member' => Heroicon::BookOpen,
            'Budget', 'ChartOfAccount', 'CustomerInvoice', 'CustomerInvoiceItem', 'JournalEntry', 'JournalEntryLine', 'Payment', 'StudentInvoice', 'StudentInvoiceItem', 'TuitionType' => Heroicon::Banknotes,
            'City', 'Country', 'District', 'Province', 'Timezone', 'Village' => Heroicon::MapPin,
            'CollageStudent', 'Student', 'Teacher', 'Lecturer', 'User' => Heroicon::Users,
            'Course', 'Curriculum', 'Subject', 'ClassStudent', 'SchoolClass' => Heroicon::AcademicCap,
            'Department', 'Employee', 'EmploymentContract', 'LeaveRequest', 'PayrollComponent', 'Position', 'SalarySlip', 'SalarySlipComponent' => Heroicon::Identification,
            'Faculty', 'StudyPlan', 'StudyPlanItem', 'StudyProgram', 'Thesis' => Heroicon::BuildingLibrary,
            'AiPromptTemplate' => Heroicon::Sparkles,
            'GoodsReceipt', 'GoodsReceiptItem', 'ProcurementCategory', 'ProcurementItem', 'PurchaseOrder', 'PurchaseOrderItem', 'PurchaseRequisition', 'PurchaseRequisitionItem', 'RequestForQuotation', 'RfqItem', 'RfqVendor', 'Vendor', 'VendorBill', 'VendorBillItem', 'StockAdjustment', 'StockAdjustmentLine', 'StockItem', 'StockLevel', 'StockMove', 'Warehouse' => Heroicon::Truck,
            'Module', 'Organization', 'OrganizationSetting', 'Tenant', 'TenantModule', 'TenantRole', 'TenantSetting', 'UserTenantRole', 'SubscriptionLog', 'SubscriptionPlan' => Heroicon::Cog6Tooth,
            default => static::navigationIcon(static::moduleNameFromClass($modelClass)),
        };
    }

    public static function module(string $module): string
    {
        return static::text(Str::headline($module));
    }

    public static function navigationIcon(string $module): string|UnitEnum
    {
        return match ($module) {
            'Campus' => Heroicon::AcademicCap,
            'Core' => Heroicon::BuildingOffice2,
            'Employee' => Heroicon::Identification,
            'Enrollment' => Heroicon::ClipboardDocumentCheck,
            'Finance' => Heroicon::Banknotes,
            'Global' => Heroicon::GlobeAlt,
            'Library' => Heroicon::BookOpen,
            'Monitoring' => Heroicon::ShieldCheck,
            'Procurement' => Heroicon::Truck,
            'Inventory' => Heroicon::Cube,
            'School' => Heroicon::AcademicCap,
            'Exam' => Heroicon::ClipboardDocumentCheck,
            'Ai' => Heroicon::Sparkles,
            default => Heroicon::RectangleStack,
        };
    }

    protected static function moduleNameFromClass(string $modelClass): string
    {
        return str($modelClass)
            ->after('Modules\\')
            ->before('\\')
            ->toString();
    }

    public static function isIndonesian(): bool
    {
        return app()->getLocale() === 'id';
    }

    protected static function translateWord(string $word): string
    {
        $key = strtolower($word);

        if (array_key_exists($word, static::PHRASES)) {
            return static::PHRASES[$word];
        }

        if (array_key_exists($key, static::WORDS)) {
            $translated = static::WORDS[$key];
            // Preserve initial capitalization from the original word
            if (strlen($word) > 0 && ctype_upper($word[0])) {
                return ucfirst($translated);
            }

            return $translated;
        }

        if (preg_match('/^[A-Z0-9]{2,}$/', $word) === 1) {
            return $word;
        }

        return $word;
    }
}
